In [65]:
from pycryptosat import Solver
import time
s = Solver()

solver = Solver()

# with open("./tva15.cnf", "r") as x:
#     for i,line in enumerate(x):
#         line = line.strip()
#         # if(line[0]=="p" or line[0]=="c"):
#         if "p" in line or "c" in line:
#             continue

#         out = [int(x) for x in line.split()[:-1]]
#         # solver.add_clause(out)
# #         print(out)
#         if(i==655727-1): # line no. 655243
#             st=out
#         elif(i==655728-1):
#             end = out
#         elif(i==655729-1):
#             timestamp = out
#         else:
#             solver.add_clause(out)
blockClause = []
with open("./tva15.cnf", "r") as x:
    for i,line in enumerate(x):
        line = line.strip()
        # if(line[0]=="p" or line[0]=="c"):
        if "p" in line or "c" in line:
            continue

        out = [int(x) for x in line.split()[:-1]]
        # solver.add_clause(out)
#         print(out)
        if(i>=1026942-1 and i<1026959-1):
            blockClause.append(out)
            continue
        if(i==1026993-1): # line no. 655243
            st=out
            continue
        elif(i==1026995-1):
            end = out
            continue
        elif(i==1026997-1):
            timestamp = out
            continue
        
        solver.add_clause(out)
print(st)
print(end)
print(timestamp)
def deform(clause,val):
    val = list((bin(val)[2:]).zfill(32))
    
    val = val[::-1]
    
    for i in range(len(clause)-1):
        clause[i] = abs(clause[i])
        if(val[i]=="0"):
            clause[i]*=-1
    return clause
sols = None
def check(solver,blocks,start_nonce,end_nonce,time_):
#     print(id(solver))
    block_ = []
    global sols
    global st,end,timestamp
    st = deform(st,start_nonce)
    end = deform(end,end_nonce)
    for i in range(len(blockClause)):
        block_.extend(deform(blockClause[i],blocks[i]-1))
    timestamp = deform(timestamp,time_)
#     end_range = 497822589
    # end_range = 11
    start = time.time()
    isSAT, sols = solver.solve(st+end+timestamp+block_)
    # res, isSAT = solver.solve()
    done = time.time()
    elapsed = done - start
    print(elapsed)
#     print(isSAT)
    return isSAT
print("checking")

[-70805, 70806, 70807, -70808, 70809, -70810, 70811, 70812, 70813, -70814, -70815, -70816, -70817, -70818, -70819, -70820, -70821, -70822, 70823, 70824, 70825, 70826, 70827, 70828, -70829, 70830, 70831, 70832, -70833, -70834, -70835, -70836, 207503]
[70837, 70838, -70839, -70840, 70841, -70842, 70843, 70844, 70845, -70846, -70847, -70848, -70849, -70850, -70851, -70852, -70853, -70854, 70855, 70856, 70857, 70858, 70859, 70860, -70861, 70862, 70863, 70864, -70865, -70866, -70867, -70868, 207504]
[-70869, -70870, 70871, -70872, -70873, 70874, 70875, 70876, -70877, 70878, -70879, 70880, 70881, 70882, 70883, 70884, 70885, -70886, -70887, 70888, 70889, -70890, 70891, -70892, -70893, 70894, 70895, 70896, -70897, -70898, 70899, -70900, 207505]
checking


In [55]:
# blockClause

In [59]:
genesys_block = [16777216, 0, 0, 0, 0, 0, 0, 0, 0, 1000599037, 2054886066, 2059873342, 1735823201, 2143820739, 2290766130, 983546026, 1260281418, 699096905, 4294901789, 250508269]
second_block = [16777216,1711699388,2939744218,3252212977,2893103710,2128873143,1431457499,3808690176,0,1803429671,533048842,3073754577,1455291121,3996402020,4104720509,1827684636,4251965418,2004092497,2980447514,4043570730]
# block  = genesys_block

In [27]:
print(check(solver,block,4043570728,4043570731,2980447514))

58.030606508255005
True


In [49]:
print(check(solver,second_block,4043570728,4043570731,2980447514))

541.0479667186737
False


In [66]:
print(check(solver,genesys_block,497822587,497822589,4294901789))

In [64]:
print(check(solver,genesys_block,497822587,497822589,4294901789))

0.06219816207885742
False


In [30]:
with open("./tva5.cnf", "r") as x:
    for i,line in enumerate(x):
        line = line.strip()
        # if(line[0]=="p" or line[0]=="c"):
        if "p" in line or "c" in line:
            continue

        out = [int(x) for x in line.split()[:-1]]
        # solver.add_clause(out)
#         print(out)
        for o in out:
            if(o<0):
                sol = toggle(sols[o])
            else:
                sol = sols[o]
            b[i]+=sol
        # if(i==655665-1): # line no. 655243
        #     st=out
        # elif(i==655666-1):
        #     end = out
        # elif(i==655667-1):
        #     timestamp = out
        # else:
        #     solver.add_clause(out)

In [20]:
# a.tolist()

In [16]:
def toggle(a):
    if(a):
        return False
    else:
        return True

In [28]:
import numpy as np
b = np.zeros(656312,dtype=np.uint8)
print(b)

[0 0 0 ... 0 0 0]


In [29]:
b

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [31]:
import numpy as np

np.save("b.npy",b)

In [32]:
a

array([0, 2, 2, ..., 0, 0, 0], dtype=uint8)

In [35]:
print((a==b).sum())

212935
443377


In [33]:
b

array([0, 1, 1, ..., 0, 0, 0], dtype=uint8)